[package]
name = "MACLang"
version = "0.1.0"
authors = ["Michael Cooper <mc454916@ohio.edu>"]
edition = "2018"

[lib]
name = "lib"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
